### ISSUE TITLE
Replace current webdav-client or write our own.

### ISSUE THREAD

**Issue by kwisatz** [tentwentyfour/nextcloud-link#26]
https://github.com/OpenMarshal/npm-WebDAV-Client still uses the deprecated `request` module. 

We should either find alternative implementations (e.g. https://github.com/perry-mitchell/webdav-client/) or alternatively write our own using either the `fetch` API or e.g. `axios`).

**Comment by floriansimon1** [comment]
+1000

I guess the performance issue come from npm-WebDAV-Client and I suppose we could actually benefit a lot from an upgrade

**Comment by kwisatz** [comment]
Together with @fedus and @lattam we had some ideas for performance improvements. Some in the client, but some also through extending the Nextcloud API, giving us OCS endpoints to replace the natively slow WebDAV calls.
I don't know if either one has some numbers on the impact of `webdav-client` on all this from profiling ?
