### ISSUE TITLE
Unable to save files from stream.

### ISSUE THREAD

**Issue by deyanmakedonski** [tentwentyfour/nextcloud-link#27]
I’m unable to upload a file from a stream reader from my file system. The main problem comes on large files, files smaller than a 1MB are uploaded successfully. But files like 3.8MB are just uploaded as a 0 bytes.

Am i missing something? It should work with client.uploadFromStream(path, fs.createReadStream(“/Archive.zip”)), right?

**Comment by kwisatz** [comment]
Hi @deyanmakedonski could you please give us a little more information about your set-up?
E.g. are you working on a development environment running a Nextcloud instance in a docker container? Or is this a production set-up with `php7.4-fpm` behind an `nginx` server, or … ? 

Can you rule out stuff like `max_upload_size` and `post_max_size` in the PHP configuration?

Do you have any error messages or logs that you could join?

**Comment by deyanmakedonski** [comment]
It was a server configuration issue as you suggested. Thanks.
