### ISSUE TITLE
Empty file contents from uploadFromStream

### ISSUE THREAD

**Issue by Mangatt** [tentwentyfour/nextcloud-link#45]
Hi,
this simple upload code fails to upload contents of file. In this case, file is created, no error is emitted, but Nextcloud file size is 0 B.

```js
const stream = fs.createReadStream('test/test.png')
await client.uploadFromStream('/test/test.png', stream)
```
**Versions:**
nextcloud-link: 1.2.9
nextcloud: 22.2.5
Node: 17.5.0

Anyone has an idea what might be causing this?

**Comment by Mangatt** [comment]
Strangely, just one direction is problematic, downloading works just fine:
```js
const out = fs.createWriteStream('test/test.png')
await client.downloadToStream('/test/test.png', out)
await finished(out)
```

**Comment by Mangatt** [comment]
Ok, never mind, it was caused by server config recommended by Nextcloud. For future reference, it was `fastcgi_request_buffering off` nginx directive in our case.

**Comment by kwisatz** [comment]
Thanks you @Mangatt for leaving the information about what caused this problem here.
We'll try to look into why this is causing problems with the upload stream.
