### ISSUE TITLE
Documentation for extraProperties

### ISSUE THREAD

**Issue by Mangatt** [tentwentyfour/nextcloud-link#46]
It would be great to have documentation and/or examples for `extraProperties` in `getFolderProperties` and `getFolderFileDetails`. In current state of things it's pretty much impossible to use that.

**Comment by kwisatz** [comment]
In a nutshell, `extraProperties` is a list of optional properties that are not returned by the WebDAV interface by default.
Which properties get returned by default and which ones are available at request can be read here: https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#requesting-properties

An example that requests the Owncloud extra property `fileid` on top of the default properties would be:

```typescript
const fileId = createOwnCloudFileDetailProperty('fileid', true);
const documentList  = await client.getFolderFileDetails('/Documents', [fileId]);
 for (const directory of documentList) {
    const folderId = directory.extraProperties.fileid;
}
```

You can find more example for both `OwnCloud` and `Nextcloud`-specific properties inside the [webdav jest tests, e.g. from line 486](https://github.com/tentwentyfour/nextcloud-link/blob/master/tests/webdav-jest.ts#L486).
