### ISSUE TITLE
Downloaded image using get / downloadToStream is broken

### ISSUE THREAD

**Issue by mfachmirizal** [tentwentyfour/nextcloud-link#48]
Hello, I have some image files on NextCloud.
I tried to get the image using:

`await client.get('/newUpload/uploaded.jpg');`
and
`await client.downloadToStream('/newUpload/uploaded.jpg', fs.createWriteStream('D:\\targetdir\\uploaded.jpg'));`

but both of them returning **broken image**.
![corupted](https://user-images.githubusercontent.com/14245898/159952814-ba331e63-cefa-4c10-a8e2-baef8599ce98.PNG)

How can I get my image file properly?

or is there anyway to get the direct image url ?, Because I need to show my uploaded image to my web.

Thanks

**Comment by kwisatz** [comment]
Hi @mfachmirizal,

`get` failing is a known issue (#39) however, we've not yet seen `downloadToStream` failing. On the other hand, we have never tested this on Windows. How are you running this, as an electron app, pre-packaged, in a shell (which one?).

Could you perhaps share more details with us (such as the command line or runtime you're using) and ideally a minimal but functional example that fails?

**Comment by mfachmirizal** [comment]
> Hi @mfachmirizal,
> 
> `get` failing is a known issue (#39) however, we've not yet seen `downloadToStream` failing. On the other hand, we have never tested this on Windows. How are you running this, as an electron app, pre-packaged, in a shell (which one?).
> 
> Could you perhaps share more details with us (such as the command line or runtime you're using) and ideally a minimal but functional example that fails?

Hello @kwisatz,
Im running this as node js application. trying to make backendservice for upload and show image via nextcloud.

for beginning I just create simply node js project for testing upload/retrieve image with this lib. The upload is success, but when  I want to retrieve the image, it always corrupted.
Thankyou

**Comment by mfachmirizal** [comment]
Ahh sorry my bad, the upload process is failed in the first place... 
it's uploaded broken image. I'm really sorry for this
thankyou
